### ISSUE TITLE
Nullable is not supported in Swagger 2.0

### ISSUE THREAD

**Issue by LaQuay** [pyeve/eve-swagger#74]
Hi,
I am using _eve-sqlalchemy_ as db-manager and the output generated by _eve-swagger_ contains _nullable_ attributes, which is not supported by _Swagger 2.0_.

My model is something like:
``` python
class MyModel():
    __tablename__ = "mymodel"

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(256))
```

And the output generated contains:
``` yaml
definitions:
  MyModel:
    type: object
    properties:
      id:
        nullable: false
        type: integer
      title:
        maxLength: 256
        nullable: true
        type: string
```

Note: I have seen the issue https://github.com/pyeve/eve-swagger/issues/39, but its closed and I don't know if he was using also _eve-sqlalchemy_.

Any idea to avoid this?
Thanks!
