### ISSUE TITLE
Example is not supported in Swagger 2.0

### ISSUE THREAD

**Issue by LaQuay** [pyeve/eve-swagger#75]
Hi,
I am using _eve-sqlalchemy_ as db-manager and the output generated by _eve-swagger_ contains the _example_ attribute inside _parameters_, which is not supported by _Swagger 2.0_.

And the output generated contains:
``` yaml
parameters:
  Mymodel:
    in: path
    name: alertId
    required: true
    description: ''
    example: ''
    type: integer
```

Any idea to avoid this?
Thanks!
